backend/cms/models/link_extra_template.py
from django.contrib.postgres.fields import JSONField
from django.db import models


class LinkExtraTemplate(models.Model):
    name = models.CharField(250)
    alias = models.CharField(60)
    thumbnail = models.CharField(250)
    url = models.CharField(250)
    post_data = JSONField(250)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

backend/cms/models/postal_code_extra.py
from cms.models.extra import Extra


class PostalCodeExtra(Extra):

    def url(self):
        return self.template.url + self.site.postal_code

backend/cms/models/site.py
"""
Database model representing an autonomous authority
"""
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.http import Http404
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class Site(models.Model):
    """
    Class to generate site database objects
    """
    ACTIVE = 'acti'
    HIDDEN = 'hidd'
    ARCHIVED = 'arch'

    STATUS = (
        (ACTIVE, _('Active')),
        (HIDDEN, _('Hidden')),
        (ARCHIVED, _('Archived')),
    )

    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    status = models.CharField(max_length=4, choices=STATUS)

    events_enabled = models.BooleanField(default=True)
    push_notifications_enabled = models.BooleanField(default=True)
    push_notification_channels = ArrayField(models.CharField(max_length=60), blank=True)

    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)
    postal_code = models.CharField(max_length=10)

    admin_mail = models.EmailField()

    created_date = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)

    statistics_enabled = models.BooleanField(default=False)
    matomo_url = models.CharField(max_length=150, blank=True, default='')
    matomo_token = models.CharField(max_length=150, blank=True, default='')
    matomo_ssl_verify = models.BooleanField(default=True)

    @property
    def languages(self):
        language_tree_nodes = self.language_tree_nodes.select_related('language').all()
        return [language_tree_node.language for language_tree_node in language_tree_nodes]

    @property
    def default_language(self):
        tree_root = self.language_tree_nodes.filter(level=0).first()
        return tree_root.language if tree_root else None

    @classmethod
    def get_current_site(cls, request):
        if not hasattr(request, 'resolver_match'):
            return None
        site_slug = request.resolver_match.kwargs.get('site_slug')
        if not site_slug:
            return None
        site = cls.objects.filter(slug=site_slug)
        if not site.exists():
            raise Http404
        return site.first()

    def __str__(self):
        """Function that provides a string representation of this object

        Returns: String
        """
        return self.name

    class Meta:
        default_permissions = ()
        permissions = (
            ('manage_regions', 'Can manage regions'),
        )

backend/cms/views/general.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def index(request):
    return render(request, 'dashboard.html')

def handler400(request):
    ctx = {'code': 400, 'title': 'Bad request', 'message': 'Die Anfrage war fehlerhaft aufgebaut.'}
    response = render(request, 'http_error.html', ctx)
    response.status_code = 400
    return response

def handler403(request):
    ctx = {'code': 403, 'title': 'Forbidden', 'message': 'In der Anfrage wurde nicht die notwendige Berechtigung übermittelt.'}
    response = render(request, 'http_error.html', ctx)
    response.status_code = 403
    return response

def handler404(request):
    ctx = {'code': 404, 'title': 'Seite nicht gefunden', 'message': 'Die von Ihnen angeforderte Seite konnte leider nicht gefunden werden.'}
    response = render(request, 'http_error.html', ctx)
    response.status_code = 404
    return response

def handler500(request):
    ctx = {'code': 500, 'title': 'Internal Server Error', 'message': 'Es ist ein unerwarteter Fehler aufgetreten.'}
    response = render(request, 'http_error.html', ctx)
    response.status_code = 500
    return response

def csrf_failure(request):
    return render(request, 'csrf_failure.html')

backend/cms/views/registration.py
from django.contrib import messages
from django.contrib.auth import logout as django_logout
from django.contrib.auth import views as auth_views
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from ..util import auth


def login(request):
    return auth_views.LoginView.as_view(template_name='registration/login.html', authentication_form=auth.LoginForm)(request)

def logout(request):
    django_logout(request)
    messages.info(request, 'Sie wurden erfolgreich abgemeldet.')
    return HttpResponseRedirect(reverse('login'))

def password_reset_done(request):
    messages.info(request, 'Eine Nachricht mit Anweisungen zum Zurücksetzen Ihres Passwort wurde an die angegebene E-Mail Adresse geschickt.')
    return HttpResponseRedirect(reverse('password_reset'))

def password_reset_confirm(request):
    return auth_views.password_reset_confirm(template_name='registration/password_reset_confirm.html')(request)

def password_reset_complete(request):
    messages.success(request, 'Ihr Passwort wurde erfolgreich geändert. Sie können sich jetzt mit dem neuen Passwort einloggen.')
    return  HttpResponseRedirect(reverse('login'))

backend/cms/views/utils.py
from ..models import DocumentForm


def save_file(request):
    status = 0
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            status = 1
    else:
        form = DocumentForm()

    return {'form': form, 'status': status}

backend/cms/templates/language_tree/tree_node.html
{% extends "_base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
{% load widget_tweaks %}
<form method="post">
    {% csrf_token %}
    <div class="flex flex-wrap mb-4">
        <div class="w-2/5 flex flex-wrap flex-col justify-center">
            <h2 class="heading font-normal">
	            {% if form.initial %}
		            {% blocktrans %}Edit language tree node{% endblocktrans %}
	            {% else %}
		            {% trans 'Add language' %}
	            {% endif %}
            </h2>
        </div>
        <div class="w-3/5 flex justify-end">
            <input type="submit" name="submit_publish" class="cursor-pointer bg-blue hover:bg-blue-dark text-white font-bold py-3 px-4 rounded" value="{% trans 'Save' %}" />
        </div>
    </div>

    <div class="flex flex-wrap">
        <div class="w-2/3 pl-2">
	        {{form.errors}}
            <div class="w-full px-4 py-2 rounded border border-solid border-grey-light shadow bg-white">
                <div class="py-2 border-b solid border-grey-lighter mb-2">
                    <label for="language" class="block mb-2 font-bold">{% trans 'Language' %}</label>
                    <div class="relative my-2">
                        {% render_field form.language id="language" class="block appearance-none w-full bg-grey-lighter border border-grey-lighter text-grey-darkest py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-grey" %}
                        <div class="pointer-events-none absolute pin-y pin-r flex items-center px-2 text-grey-darkest">
                            <img src="{% static 'svg/select-down-arrow.svg' %}" class="fill-current h-4 w-4" />
                        </div>
                    </div>
                </div>
                <div class="py-2 border-b solid border-grey-lighter mb-2">
                    <label for="parent" class="font-bold mb-2 block">{% trans 'Source Language' %}</label>
                    <div class="relative my-2">
                        {% render_field form.parent id="parent" class="block appearance-none w-full bg-grey-lighter border border-grey-lighter text-grey-darkest py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-grey" %}
                        <div class="pointer-events-none absolute pin-y pin-r flex items-center px-2 text-grey-darkest">
                            <img src="{% static 'svg/select-down-arrow.svg' %}" class="fill-current h-4 w-4" />
                        </div>
                    </div>
                </div>
                <div class="py-2 border-b solid border-grey-lighter mb-2">
	                <div class="py-2 pb-4">
		                <label for="active" class="font-bold">{% trans 'Activate language' %}</label>
		                {% render_field form.active id="active" class="" %}
	                </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

backend/cms/templates/language_tree/tree_row.html
{% load i18n %}

<tr class="border-t border-solid border-grey-lighter hover:bg-grey-lightest{% if node.depth > 0 %} child level-{{node.depth}}{% endif %}">
    <td class="single_icon">
        <span class="block py-3 pl-4 pr-2 cursor-move">
            <i data-feather="move" class="text-grey-darkest"></i>
        </span>
    </td>
	<td>
		<a href="{% url 'edit_language_tree_node' language_tree_node_id=node.id region_slug=region.slug %}" class="block py-3 px-2 text-grey-darkest">
			{{ node.translated_name }}
		</a>
	</td>
    <td class="pl-2 pr-4" width="125">
	    {% if node.active %}
		    <i data-feather="check" class="text-grey-darkest"></i>
	    {% else %}
		    <i data-feather="x" class="text-grey-darkest"></i>
	    {% endif %}
    </td>
</tr>

backend/cms/templates/media/edit.html
{% extends "_base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
    <div class="w-full max-w-full">
        <form id="upload_form" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="flex items-center justify-start mt-6">
                <button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded">
	                {% trans 'Submit' %}
                </button>
                <a href="{% url 'media' region_slug=region.slug %}" class="ml-1 bg-grey-dark hover:bg-integreat hover:text-grey-darkest text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    {% trans 'Return' %}
                </a>
            </div>
        </form>
    </div>
{% endblock %}

backend/cms/templates/media/list.html
{% extends "_base.html" %}
{% load i18n %}
{% block content %}
<div class="table-header">
    <div class="flex flex-wrap">
        <form class="table-search relative w-1/2">
            <i data-feather="search" class="absolute"></i>
            <input type="search" placeholder="{% trans 'Search' %}" class="h-full pl-10 pr-4 rounded shadow">
        </form>
        <div class="w-1/2 flex flex-wrap justify-end">
            <a href="{% url 'new_upload_file' document_id='0' region_slug=region.slug %}" class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
	            {% trans 'Upload File' %}
            </a>
        </div>
    </div>
</div>

<div class="table-listing">
    <table class="w-full mt-4 rounded border border-solid border-grey-light shadow bg-white">
        <thead>
            <tr class="border-b border-solid border-grey-light">
                <th class="text-sm text-left uppercase p-3 pl-4">{% trans 'Name' %}</th>
                <th class="text-sm text-left uppercase p-3">{% trans 'Date' %}</th>
                <th class="text-sm text-left uppercase p-3 pr-4">{% trans 'Operations' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for obj in documents %}
            <tr class="border-t border-solid border-grey-lighter hover:bg-grey-lightest">
                <td class="pl-2" rel="{{ obj.description }}">
                    <a href="{% url 'edit_file' document_id=obj.pk region_slug=region.slug %}" class="block py-3 px-2 text-grey-darkest">
                        {{ obj.document.name }}
                    </a>
                </td>
	            <td>
                    <a href="{% url 'edit_file' document_id=obj.pk region_slug=region.slug %}" class="block py-3 px-2 text-grey-darkest">
                        {{ obj.uploaded_at }}
                    </a>
                </td>
	            <td class="pl-3 pr-4">
                    <a href="{{ obj.document.url }}" rel="{{ obj.description }}" class="py-3" style="padding-right: 4px;">
                        <i data-feather="eye" class="text-grey-darkest"></i>
                    </a>
                    <a href="{{ obj.document.url }}" rel="{{ obj.description }}" class="py-3" style="padding-right: 4px;" download>
                        <i data-feather="download" class="text-grey-darkest"></i>
                    </a>
                    <form method="post" action="{% url 'delete_file' document_id=obj.pk region_slug=region.slug %}" class="inline-block py-3" style="padding-right: 4px;">
                        {% csrf_token %}
                        <button type="submit" class="bg-white"><i data-feather="trash-2" class="text-grey-darkest"></i></button>
                    </form>
                    <a href="{% url 'edit_file' document_id=obj.pk region_slug=region.slug %}" class="py-3">
                        <i data-feather="edit" class="text-grey-darkest"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

backend/cms/templates/media/mediaedit.html
{% extends "_base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
    <div class="w-full max-w-full">
        <form id="upload_form" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="flex items-center justify-start mt-6">
                <button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded">
	                {% trans 'Submit' %}
                </button>
                <a href="{% url 'media' region_slug=region.slug %}" class="ml-1 bg-grey-dark hover:bg-integreat hover:text-grey-darkest text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    {% trans 'Return' %}
                </a>
            </div>
        </form>
    </div>
{% endblock %}

backend/cms/templates/media/mediaupload.html
{% extends "_base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
    <div class="w-full max-w-full">
        <form id="upload_form" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="flex items-center justify-start mt-6">
                <button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded">
	                {% trans 'Submit' %}
                </button>
                <a href="{% url 'media' site_slug=site.slug %}" class="ml-1 bg-grey-dark hover:bg-integreat hover:text-grey-darkest text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    {% trans 'Return' %}
                </a>
            </div>
        </form>
    </div>
{% endblock %}

backend/cms/templates/organizations/list_row.html
<tr class="border-t border-solid border-grey-lighter hover:bg-grey-lightest">
    <td class="pl-2">
        <a href="{% url 'edit_organization' organization_id=organization.id %}" class="block py-3 px-2 text-grey-darkest">
            {{ organization.name }}
        </a>
    </td>
	<td>
        <a href="{% url 'edit_organization' organization_id=organization.id %}" class="block py-3 px-2 text-grey-darkest">
            {{ organization.slug }}
        </a>
	</td>
	<td class="pr-2">
        <a href="{% url 'edit_organization' organization_id=organization.id %}" class="block py-3 px-2 text-grey-darkest">
            {{ organization.thumbnail }}
        </a>
	</td>
</tr>

backend/cms/templates/organizations/organization.html
{% extends "_base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
{% load widget_tweaks %}
<form method="post">
    {% csrf_token %}
    <div class="flex flex-wrap mb-4">
        <div class="w-2/5 flex flex-wrap flex-col justify-center">
            <h2 class="heading font-normal">
	            {% if form.initial %}
		            {% with form.name.value as organization_name %}
			            {% blocktrans %}Edit organization "{{ organization_name }}"{% endblocktrans %}
		            {% endwith %}
	            {% else %}
		            {% trans 'Create new organization' %}
	            {% endif %}
            </h2>
        </div>
        <div class="w-3/5 flex justify-end">
            <input type="submit" name="submit_save" class="cursor-pointer bg-grey hover:bg-grey-dark text-white font-bold py-3 px-4 rounded mr-2" value="{% trans 'Save' %}" />
            <input type="submit" name="submit_publish" class="cursor-pointer bg-blue hover:bg-blue-dark text-white font-bold py-3 px-4 rounded" value="{% trans 'Publish' %}" />
        </div>
    </div>

    <div class="flex flex-wrap">
	    <div class="w-1/2 pr-2">
		    {{form.errors}}
		    <div class="w-full mb-4 rounded border border-solid border-grey-light shadow bg-white">
				<div class="w-full p-4 rounded bg-blue-dark">
					<h3 class="heading font-bold text-white">{% trans 'General Settings' %}</h3>
				</div>
				<div class="w-full p-4">

					<!-- General Options for organization management -->
                    <label for="id_name" class="font-bold block p-2 mb-1 cursor-pointer">{% trans "Organizationname" %}</label>
                    {% trans "Enter the organization's name here" as name_placeholder%}
                    {% render_field form.name placeholder=name_placeholder class="appearance-none block w-full bg-grey-lighter text-xl text-grey-darkest border border-grey-lighter rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-grey" %}

                    <label for="id_slug" class="font-bold block p-2 mb-1 mt-5 cursor-pointer">{% trans "Slug of the organization" %}</label>
                    {% trans "Enter the organization's slug here" as slug_placeholder%}
                    {% render_field form.slug placeholder=slug_placeholder class="appearance-none block w-full bg-grey-lighter text-xl text-grey-darkest border border-grey-lighter rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-grey" %}

                    <label for="id_thumbnail" class="font-bold block p-2 mb-1 mt-5 cursor-pointer">{% trans "Thumbnail of the organization" %}</label>
                    {% trans "Enter the organization's thumbnail here" as thumbnail_placeholder%}
                    {% render_field form.thumbnail placeholder=thumbnail_placeholder class="appearance-none block w-full bg-grey-lighter text-xl text-grey-darkest border border-grey-lighter rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-grey" %}

				</div>
			</div>
		</div>
	<div class="w-1/2 pl-2">
		<div class="w-full mb-4 rounded border border-solid border-grey-light shadow bg-white">
			<div class="w-full p-4 rounded bg-blue-dark">
				<h3 class="heading font-bold text-white">{% trans 'Extended Settings' %}</h3>
			</div>
			<div class="w-full p-4">
				<div class="flex w-full bg-grey-lighter">
					<img class="flex w-2/3 p-2 h-40 pt-4 pb-4 justify-start" src="https://tailwindcss.com/img/card-top.jpg">
					</img>
					<div class="flex h-48 w-1/3 pt-4 p-2 pb-4 justify-end">
						{% render_field form.icon id="icon" class="image-field" %}
						<label class="w-64 flex flex-col items-center px-4 py-6 bg-white text-blue rounded-lg shadow-lg tracking-wide uppercase border border-blue cursor-pointer hover:bg-blue hover:text-white">
							<svg class="w-1/4 h-1/4" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
								<path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
							</svg>
							<span class="mt-2 text-base leading-normal text-center">{% trans 'Set icon' %}</span>
							<input type='filename' class="hidden" />
						</label>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>
</form>
{% endblock %}